# declares which docker image should be used
# https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-an-image
image: maven:3-jdk-8

# define shell script which executed by GitLab Runner
build:
  # -B -> non-interactive batch mode
  script:
  - "mvn install -B"
  - "cat target/site/jacoco/index.html"
