# declares which docker image should be used
# https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-an-image
image: maven:3-jdk-8

# will be executed before each job
before_script:
  - "ls -la"
  - "curl --verbose --fail --location --header \"PRIVATE-TOKEN: ${PRIVATE_TOKEN_CATALOG}\" --url \"https://gitlab.in.htwg-konstanz.de/mibay/swqs-catalog/-/jobs/artifacts/master/download?job=maven%3Averify\" -o artifacts.zip"
  - "mkdir -p /root/.m2/repository/de/htwg/swqs/catalog/0.0.1-SNAPSHOT/"
  - "unzip artifacts.zip -d /root/.m2/repository/de/htwg/swqs/catalog/0.0.1-SNAPSHOT/"

maven:verify:
  stage: test
  script:
  - "mvn verify --batch-mode"
  - "cat target/site/jacoco/index.html"
  - "mv target/*.jar ."
  artifacts:
    when: on_success
    expire_in: 20d
    paths:
      - "*.jar"