# declares which docker image should be used
# https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-an-image
image: maven:3-jdk-8

# will be executed before each job
before_script:
  - "curl --verbose --fail --location --header \"PRIVATE-TOKEN: $PRIVATE_TOKEN_CATALOG\" --url \"https://gitlab.in.htwg-konstanz.de/mibay/swqs-catalog/-/jobs/artifacts/master/download?job=maven%3Averif\" -o artifacts.zip"
  - "mkdir .m2/repository/de/htwg/swqs/catalog/0.0.1-SNAPSHOT/"
  - "unzip artifacts.zip -d .m2/repository/de/htwg/swqs/catalog/0.0.1-SNAPSHOT/"

# we run just the test goal because the dependency to the de.htwg.swqs.catalog project
# can not be fulfilled in the ci environment
maven:test:
  stage: test
  script:
  - "mvn test --batch-mode"
  - "cat target/site/jacoco/index.html"
  - "mv target/*.jar ."