# declares which docker image should be used
# https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-an-image
image: maven:3-jdk-8

# Cache downloaded dependencies and plugins between builds.
cache:
  paths:
    - .m2/

variables:
  MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2

maven:package:
  stage: test
  script:
  - "mvn package --batch-mode"
  - "cat target/site/jacoco/index.html"
  - "mv target/*.jar ."
  artifacts:
    when: on_success
    expire_in: 20d
    paths:
      - "*.jar"
